modLoader="javafml"
loaderVersion="${loader_version_range}"

license="ARR"

[[mods]]
modId="shopcore"
version="1.0.0"
displayName="Farmer's Shop Core"

authors="y271727uy"

description='''${mod_description}'''


[[dependencies.shopcore]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.shopcore]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


